import { $MapRegion, $OverlayManager, $MapUpdateFastConfig, $MapBlock, $LeveledRegion, $MapTileChunk, $MapTile } from "@package/xaero/map/region";
import { $MapTilePool } from "@package/xaero/map/pool";
import { $Minecraft } from "@package/net/minecraft/client";
import { $Iterator, $Queue, $ArrayList } from "@package/java/util";
import { $WorldDataHandler } from "@package/xaero/map/file/worldsave";
import { $ClientPacketListener, $ClientLevel } from "@package/net/minecraft/client/multiplayer";
import { $BlockPos$MutableBlockPos, $BlockPos_, $Registry, $HolderLookup } from "@package/net/minecraft/core";
import { $ClientSyncedTrackedPlayerManager } from "@package/xaero/map/radar/tracker/synced";
import { $BlockState_, $StateHolder } from "@package/net/minecraft/world/level/block/state";
import { $Field } from "@package/java/lang/reflect";
import { $MessageBox } from "@package/xaero/map/gui/message";
import { $Runnable_, $Object, $Runnable } from "@package/java/lang";
import { $MessageBoxRenderer } from "@package/xaero/map/gui/message/render";
import { $Level } from "@package/net/minecraft/world/level";
import { $MapRunnerTask } from "@package/xaero/map/task";
import { $MapWorld, $MapDimension } from "@package/xaero/map/world";
import { $MultiTextureRenderTypeRendererProvider } from "@package/xaero/map/graphics/renderer/multitexture";
import { $Item } from "@package/net/minecraft/world/item";
import { $Fluid } from "@package/net/minecraft/world/level/material";
import { $MapSaveLoad, $RegionDetection } from "@package/xaero/map/file";
import { $TextureUploader, $CustomVertexConsumers } from "@package/xaero/map/graphics";
import { $Biome } from "@package/net/minecraft/world/level/biome";
import { $LocalPlayer } from "@package/net/minecraft/client/player";
import { $MapRegionHighlightsPreparer, $HighlighterRegistry } from "@package/xaero/map/highlight";
import { $LevelChunk } from "@package/net/minecraft/world/level/chunk";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $BranchTextureRenderer } from "@package/xaero/map/region/texture";
import { $BiomeGetter, $BlockTintProvider, $BiomeColorCalculator } from "@package/xaero/map/biome";
import { $ByteBufferDeallocator } from "@package/xaero/map/deallocator";
import { $ControlsHandler } from "@package/xaero/map/controls";
import { $ResourceKey_, $ResourceKey } from "@package/net/minecraft/resources";
import { $CaveStartCalculator } from "@package/xaero/map/misc";
import { $Block } from "@package/net/minecraft/world/level/block";
import { $DimensionType, $DimensionType_ } from "@package/net/minecraft/world/level/dimension";
import { $BlockStateShortShapeCache, $BrokenBlockTintCache } from "@package/xaero/map/cache";
export * as capabilities from "@package/xaero/map/capabilities";
export * as pool from "@package/xaero/map/pool";
export * as graphics from "@package/xaero/map/graphics";
export * as region from "@package/xaero/map/region";
export * as gui from "@package/xaero/map/gui";
export * as server from "@package/xaero/map/server";
export * as misc from "@package/xaero/map/misc";
export * as file from "@package/xaero/map/file";
export * as mcworld from "@package/xaero/map/mcworld";
export * as world from "@package/xaero/map/world";
export * as core from "@package/xaero/map/core";
export * as task from "@package/xaero/map/task";
export * as highlight from "@package/xaero/map/highlight";
export * as executor from "@package/xaero/map/executor";
export * as controls from "@package/xaero/map/controls";
export * as biome from "@package/xaero/map/biome";
export * as deallocator from "@package/xaero/map/deallocator";
export * as util from "@package/xaero/map/util";
export * as message from "@package/xaero/map/message";
export * as cache from "@package/xaero/map/cache";
export * as palette from "@package/xaero/map/palette";
export * as radar from "@package/xaero/map/radar";

declare module "@package/xaero/map" {
    export class $MapRunner implements $Runnable {
        run(): void;
        stop(): void;
        doTasks(arg0: $MapProcessor): void;
        addTask(arg0: $MapRunnerTask): void;
        constructor();
    }
    export class $MapWriter {
        getSectionBasedHeight(arg0: $LevelChunk, arg1: number): number;
        requestCachedColoursClear(): void;
        /**
         * @deprecated
         */
        loadBlockColourFromTexture(arg0: $BlockState_, arg1: boolean, arg2: $Level, arg3: $Registry<$Block>, arg4: $BlockPos_): number;
        getMapProcessor(): $MapProcessor;
        writeMap(arg0: $Level, arg1: $Registry<$Block>, arg2: number, arg3: number, arg4: number, arg5: $Registry<$Biome>, arg6: $BiomeColorCalculator, arg7: $OverlayManager, arg8: boolean, arg9: boolean, arg10: boolean, arg11: boolean, arg12: boolean, arg13: $BlockPos$MutableBlockPos, arg14: $BlockTintProvider, arg15: number, arg16: $MapUpdateFastConfig): boolean;
        resetPosition(): void;
        isInvisible(arg0: $BlockState_, arg1: $Block, arg2: boolean): boolean;
        isGlowing(arg0: $BlockState_): boolean;
        getUpdateCounter(): number;
        hasVanillaColor(arg0: $BlockState_, arg1: $Level, arg2: $Registry<$Block>, arg3: $BlockPos_): boolean;
        shouldOverlay(arg0: $StateHolder<never, never>): boolean;
        setMapProcessor(arg0: $MapProcessor): void;
        writeChunk(arg0: $Level, arg1: $Registry<$Block>, arg2: number, arg3: boolean, arg4: $Registry<$Biome>, arg5: $OverlayManager, arg6: boolean, arg7: boolean, arg8: boolean, arg9: boolean, arg10: boolean, arg11: $BlockPos$MutableBlockPos, arg12: $BlockTintProvider, arg13: number, arg14: number, arg15: number, arg16: number, arg17: number, arg18: number, arg19: number, arg20: number, arg21: number, arg22: $MapUpdateFastConfig): boolean;
        onRender(arg0: $BiomeColorCalculator, arg1: $OverlayManager): void;
        updateBottomRightTile(arg0: $MapRegion, arg1: $MapTileChunk, arg2: $MapTileChunk, arg3: number, arg4: number): void;
        setDirtyInWriteDistance(arg0: $Player, arg1: $Level): void;
        loadPixel(arg0: $Level, arg1: $Registry<$Block>, arg2: $MapBlock, arg3: $MapBlock, arg4: $LevelChunk, arg5: number, arg6: number, arg7: number, arg8: number, arg9: boolean, arg10: boolean, arg11: number, arg12: boolean, arg13: boolean, arg14: $Registry<$Biome>, arg15: boolean, arg16: number, arg17: $BlockPos$MutableBlockPos): void;
        static DEFAULT_RESOURCE: string[];
        static NO_Y_VALUE: number;
        static MAX_TRANSPARENCY_BLEND_DEPTH: number;
        writeFreeSinceLastWrite: number;
        constructor(arg0: $OverlayManager, arg1: $BlockStateShortShapeCache, arg2: $BiomeGetter);
        get updateCounter(): number;
    }
    export class $MapLimiter {
        regionsFitOnScreen(arg0: number): void;
        getAvailableVRAM(): number;
        onSessionFinalized(): void;
        updateAvailableVRAM(): void;
        getRegionsFitOnScreen(): number;
        applyLimit(arg0: $MapWorld, arg1: $MapProcessor): void;
        constructor();
        get availableVRAM(): number;
    }
    export class $WorldMapSession {
        init(arg0: $ClientPacketListener, arg1: number): void;
        cleanup(): void;
        static getCurrentSession(): $WorldMapSession;
        getMapProcessor(): $MapProcessor;
        static getForPlayer(arg0: $LocalPlayer): $WorldMapSession;
        getControlsHandler(): $ControlsHandler;
        isUsable(): boolean;
        constructor();
        static get currentSession(): $WorldMapSession;
        get mapProcessor(): $MapProcessor;
        get controlsHandler(): $ControlsHandler;
        get usable(): boolean;
    }
    export class $MapProcessor {
        run(arg0: $MapRunner): void;
        stop(): void;
        getClientSyncedTrackedPlayerManager(): $ClientSyncedTrackedPlayerManager;
        isEqual(arg0: string, arg1: string, arg2: string): boolean;
        getBlockStateShortShapeCache(): $BlockStateShortShapeCache;
        actuallySkippingWorldRender(): boolean;
        getMessageBox(): $MessageBox;
        getGlobalVersion(): number;
        isCurrentMapLocked(): boolean;
        regionExists(arg0: number, arg1: number, arg2: number): boolean;
        updateCaveStart(): void;
        getMapLimiter(): $MapLimiter;
        getOverlayManager(): $OverlayManager;
        getProcessedCount(): number;
        getLeveledRegion(arg0: number, arg1: number, arg2: number, arg3: number): $LeveledRegion<never>;
        getMapSaveLoad(): $MapSaveLoad;
        isDebugConfig(): boolean;
        getTilePool(): $MapTilePool;
        getFootprints(): $ArrayList<number[]>;
        isFootstepsConfig(): boolean;
        getCvc(): $CustomVertexConsumers;
        getMapItem(): $Item;
        onWorldUnload(): void;
        isFinished(): boolean;
        getMapRegionHighlightsPreparer(): $MapRegionHighlightsPreparer;
        getMaxLoadedRegionsConfig(): number;
        isProcessed(arg0: $LeveledRegion<never>): boolean;
        isCurrentMultiworldWritable(): boolean;
        onInit(arg0: $ClientPacketListener): void;
        isMapWorldUsable(): boolean;
        getMapWorld(): $MapWorld;
        getLeafMapRegion(arg0: number, arg1: number, arg2: number, arg3: boolean): $MapRegion;
        isRenderingPaused(): boolean;
        getCurrentWorldId(): string;
        initMinimapRender(arg0: number, arg1: number): void;
        isUploadingPaused(): boolean;
        isUIPaused(): boolean;
        beforeMinimapRegionRender(arg0: $MapRegion): void;
        getCurrentCaveLayer(): number;
        getCurrentDimension(): string;
        finalizeMinimapRender(): void;
        getMinimapMapRegion(arg0: number, arg1: number): $MapRegion;
        isWaitingForWorldUpdate(): boolean;
        setConsideringNetherFairPlayMessage(arg0: boolean): void;
        ignoreWorld(arg0: $Level): boolean;
        addToProcess(arg0: $LeveledRegion<never>): void;
        isWritingPaused(): boolean;
        isFlowersConfig(): boolean;
        onClientTickStart(): void;
        onRenderProcess(arg0: $Minecraft): void;
        setMainValues(): void;
        updateWorldSpawn(arg0: $BlockPos_, arg1: $ClientLevel): void;
        updateMapItem(): void;
        getMapWriter(): $MapWriter;
        serverHasMod(): boolean;
        getWorld(): $ClientLevel;
        getMessageBoxRenderer(): $MessageBoxRenderer;
        static shouldSkipWorldRender(): boolean;
        getCaveModeDepthConfig(): number;
        isReloadViewedConfig(): boolean;
        isAdjustHeightForCarpetLikeBlocksConfig(): boolean;
        updateConfigValuesForMultipleThreads(): void;
        resetRenderStartTime(): void;
        getRenderStartTimeUpdater(): $Runnable;
        setFairplayMessageReceived(arg0: boolean): void;
        getWorldDataHandler(): $WorldDataHandler;
        getCrosshairMessage(): string;
        isForceFastWritingConfig(): boolean;
        getWorldBlockTintProvider(): $BlockTintProvider;
        getWorldBlockRegistry(): $Registry<$Block>;
        getMinecraftScheduledTasks(): $Queue<$Runnable>;
        canQuickConfirmUnsynced(): boolean;
        toggleMultiworldType(arg0: $MapDimension): void;
        updateVisitedDimension(arg0: $ClientLevel): void;
        checkForWorldUpdate(): void;
        requestCurrentMapDeletion(): void;
        getBiomeColorCalculator(): $BiomeColorCalculator;
        getDimensionIdForFolder(arg0: string): $ResourceKey<$Level>;
        getWorldBlockLookup(): $HolderLookup<$Block>;
        isIgnoreMapFileLocksConfig(): boolean;
        quickConfirmMultiworld(): void;
        getHighlighterRegistry(): $HighlighterRegistry;
        getServerModNetworkVersion(): number;
        removeMapRegion(arg0: $LeveledRegion<never>): void;
        pushWriterPause(): void;
        popWriterPause(): void;
        addToRefresh(arg0: $MapRegion, arg1: boolean): void;
        removeToRefresh(arg0: $MapRegion): void;
        getWorldDimensionTypeRegistry(): $Registry<$DimensionType>;
        getBrightness(): number;
        getBrightness(arg0: number, arg1: $ClientLevel, arg2: boolean): number;
        getBrightness(arg0: boolean): number;
        onServerLevelId(arg0: number): void;
        getReloadViewedVersionConfig(): number;
        getAffectingLoadingFrequencyCount(): number;
        setServerModNetworkVersion(arg0: number): void;
        getMultiTextureRenderTypeRenderers(): $MultiTextureRenderTypeRendererProvider;
        getDimensionName(arg0: $ResourceKey_<$Level>): string;
        isConsideringNetherFairPlay(): boolean;
        fairplayMessageWasReceived(): boolean;
        getBufferDeallocator(): $ByteBufferDeallocator;
        regionDetectionExists(arg0: number, arg1: number, arg2: number): boolean;
        getAmbientBrightness(arg0: $DimensionType_): number;
        waitForLoadingToFinish(arg0: $Runnable_): void;
        getMapTile(arg0: number, arg1: number, arg2: number): $MapTile;
        popUIPause(): void;
        confirmMultiworld(arg0: $MapDimension): boolean;
        setMultiworld(arg0: $MapDimension, arg1: string): void;
        updateFootprints(arg0: number): void;
        isProcessingPaused(): boolean;
        pushUIPause(): void;
        updateDimension(arg0: $ClientLevel, arg1: $ResourceKey_<$Level>): void;
        pushIsLoading(): void;
        popIsLoading(): void;
        removeToProcess(arg0: $LeveledRegion<never>): void;
        getMapChunk(arg0: number, arg1: number, arg2: number): $MapTileChunk;
        changeWorld(arg0: $ClientLevel, arg1: $HolderLookup<$Block>, arg2: $Registry<$Block>, arg3: $Registry<$Fluid>, arg4: $Registry<$Biome>, arg5: $Registry<$DimensionType_>): void;
        getRenderStartTime(): number;
        static isWorldMultiplayer(arg0: boolean, arg1: string): boolean;
        isFinalizing(): boolean;
        static isWorldRealms(arg0: string): boolean;
        getNewWorld(): $ClientLevel;
        getSaveTime(): number;
        getCurrentMWId(): string;
        getCurrentDimId(): string;
        pushRenderPause(arg0: boolean, arg1: boolean): void;
        popRenderPause(arg0: boolean, arg1: boolean): void;
        worldBiomeRegistry: $Registry<$Biome>;
        freeFramePeriod: number;
        processorThreadPauseSync: $Object;
        mainPlayerX: number;
        mainWorldBlockRegistry: $Registry<$Block>;
        mainPlayerY: number;
        mainWorldBiomeRegistry: $Registry<$Biome>;
        mainStuffSync: $Object;
        mainWorld: $ClientLevel;
        mainWorldDimensionTypeRegistry: $Registry<$DimensionType>;
        static ROOT_FOLDER_FORMAT: number;
        selectedField: $Field;
        mainPlayerZ: number;
        renderThreadPauseSync: $Object;
        newWorldBiomeRegistry: $Registry<$Biome>;
        newWorldDimensionTypeRegistry: $Registry<$DimensionType>;
        static DEFAULT_LIGHT_LEVELS: number;
        uiSync: $Object;
        uiPauseSync: $Object;
        newWorldBlockRegistry: $Registry<$Block>;
        constructor(arg0: $MapSaveLoad, arg1: $MapWriter, arg2: $MapLimiter, arg3: $ByteBufferDeallocator, arg4: $MapTilePool, arg5: $OverlayManager, arg6: $TextureUploader, arg7: $WorldDataHandler, arg8: $BranchTextureRenderer, arg9: $MultiTextureRenderTypeRendererProvider, arg10: $CustomVertexConsumers, arg11: $BiomeColorCalculator, arg12: $BlockStateShortShapeCache, arg13: $BiomeGetter, arg14: $BrokenBlockTintCache, arg15: $HighlighterRegistry, arg16: $MapRegionHighlightsPreparer, arg17: $MessageBox, arg18: $MessageBoxRenderer, arg19: $CaveStartCalculator, arg20: $ClientSyncedTrackedPlayerManager);
        get clientSyncedTrackedPlayerManager(): $ClientSyncedTrackedPlayerManager;
        get blockStateShortShapeCache(): $BlockStateShortShapeCache;
        get messageBox(): $MessageBox;
        get globalVersion(): number;
        get currentMapLocked(): boolean;
        get mapLimiter(): $MapLimiter;
        get overlayManager(): $OverlayManager;
        get processedCount(): number;
        get mapSaveLoad(): $MapSaveLoad;
        get debugConfig(): boolean;
        get tilePool(): $MapTilePool;
        get footprints(): $ArrayList<number[]>;
        get footstepsConfig(): boolean;
        get cvc(): $CustomVertexConsumers;
        get mapItem(): $Item;
        get finished(): boolean;
        get mapRegionHighlightsPreparer(): $MapRegionHighlightsPreparer;
        get maxLoadedRegionsConfig(): number;
        get currentMultiworldWritable(): boolean;
        get mapWorldUsable(): boolean;
        get mapWorld(): $MapWorld;
        get renderingPaused(): boolean;
        get currentWorldId(): string;
        get uploadingPaused(): boolean;
        get UIPaused(): boolean;
        get currentCaveLayer(): number;
        get currentDimension(): string;
        get waitingForWorldUpdate(): boolean;
        set consideringNetherFairPlayMessage(value: boolean);
        get writingPaused(): boolean;
        get flowersConfig(): boolean;
        get mapWriter(): $MapWriter;
        get world(): $ClientLevel;
        get messageBoxRenderer(): $MessageBoxRenderer;
        get caveModeDepthConfig(): number;
        get reloadViewedConfig(): boolean;
        get adjustHeightForCarpetLikeBlocksConfig(): boolean;
        get renderStartTimeUpdater(): $Runnable;
        set fairplayMessageReceived(value: boolean);
        get worldDataHandler(): $WorldDataHandler;
        get crosshairMessage(): string;
        get forceFastWritingConfig(): boolean;
        get worldBlockTintProvider(): $BlockTintProvider;
        get worldBlockRegistry(): $Registry<$Block>;
        get minecraftScheduledTasks(): $Queue<$Runnable>;
        get biomeColorCalculator(): $BiomeColorCalculator;
        get worldBlockLookup(): $HolderLookup<$Block>;
        get ignoreMapFileLocksConfig(): boolean;
        get highlighterRegistry(): $HighlighterRegistry;
        get worldDimensionTypeRegistry(): $Registry<$DimensionType>;
        get reloadViewedVersionConfig(): number;
        get affectingLoadingFrequencyCount(): number;
        get multiTextureRenderTypeRenderers(): $MultiTextureRenderTypeRendererProvider;
        get consideringNetherFairPlay(): boolean;
        get bufferDeallocator(): $ByteBufferDeallocator;
        get processingPaused(): boolean;
        get renderStartTime(): number;
        get finalizing(): boolean;
        get newWorld(): $ClientLevel;
        get saveTime(): number;
        get currentMWId(): string;
        get currentDimId(): string;
    }
    export class $MapFullReloader {
        isResave(): boolean;
        onRenderProcess(): void;
        isPartOfReload(arg0: $MapRegion): boolean;
        static CONVERTED_WORLD_SAVE_MW: string;
        constructor(arg0: number, arg1: boolean, arg2: $Iterator<$RegionDetection>, arg3: $MapDimension, arg4: $MapProcessor);
        get resave(): boolean;
    }
}
