import { $Level } from "@package/net/minecraft/world/level";
import { $PonderScene } from "@package/net/createmod/ponder/foundation";
import { $Codec } from "@package/com/mojang/serialization";
import { $MultiBufferSource_ } from "@package/net/minecraft/client/renderer";
import { $Particle } from "@package/net/minecraft/client/particle";
import { $Selection } from "@package/net/createmod/ponder/api/scene";
import { $Camera } from "@package/net/minecraft/client";
import { $WritableLevelData } from "@package/net/minecraft/world/level/storage";
import { $ArrayList, $List, $Map } from "@package/java/util";
import { $RandomSource } from "@package/net/minecraft/util";
import { $SuperRenderTypeBuffer } from "@package/net/createmod/catnip/render";
import { $BlockSnapshot } from "@package/net/neoforged/neoforge/common/util";
import { $BlockPos, $BlockPos_ } from "@package/net/minecraft/core";
import { $BlockState_ } from "@package/net/minecraft/world/level/block/state";
import { $ResourceKey } from "@package/net/minecraft/resources";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $SchematicLevel } from "@package/net/createmod/catnip/levelWrappers";
import { $Thread } from "@package/java/lang";
import { $NeighborUpdater } from "@package/net/minecraft/world/level/redstone";
import { $TickingBlockEntity } from "@package/net/minecraft/world/level/block/entity";

declare module "@package/net/createmod/ponder/api/level" {
    export class $PonderLevel extends $SchematicLevel {
        restore(): void;
        tick(): void;
        addParticle(arg0: $Particle | null): void;
        clearMask(): void;
        setMask(arg0: $Selection | null): void;
        createBackup(): void;
        renderParticles(arg0: $PoseStack, arg1: $MultiBufferSource_, arg2: $Camera, arg3: number): void;
        pushFakeLight(arg0: number): void;
        setBlockBreakingProgress(arg0: $BlockPos_, arg1: number): void;
        addBlockDestroyEffects(arg0: $BlockPos_, arg1: $BlockState_): void;
        popLight(): void;
        renderEntities(arg0: $PoseStack, arg1: $SuperRenderTypeBuffer, arg2: $Camera, arg3: number): void;
        getBlockBreakingProgressions(): $Map<$BlockPos, number>;
        restoreBlocks(arg0: $Selection): void;
        restoringBlockSnapshots: boolean;
        neighborUpdater: $NeighborUpdater;
        static LONG_PARTICLE_CLIP_RANGE: number;
        randValue: number;
        levelData: $WritableLevelData;
        scene: $PonderScene;
        thunderLevel: number;
        random: $RandomSource;
        capturedBlockSnapshots: $ArrayList<$BlockSnapshot>;
        static MAX_ENTITY_SPAWN_Y: number;
        static NETHER: $ResourceKey<$Level>;
        static MAX_BRIGHTNESS: number;
        static SHORT_PARTICLE_CLIP_RANGE: number;
        rainLevel: number;
        oThunderLevel: number;
        static ATTACHMENTS_NBT_KEY: string;
        thread: $Thread;
        addend: number;
        renderMode: boolean;
        static OVERWORLD: $ResourceKey<$Level>;
        static TICKS_PER_DAY: number;
        oRainLevel: number;
        anchor: $BlockPos;
        static RESOURCE_KEY_CODEC: $Codec<$ResourceKey<$Level>>;
        static END: $ResourceKey<$Level>;
        static MAX_LEVEL_SIZE: number;
        static MIN_ENTITY_SPAWN_Y: number;
        blockEntityTickers: $List<$TickingBlockEntity>;
        captureBlockSnapshots: boolean;
        constructor(arg0: $BlockPos_, arg1: $Level);
        set mask(value: $Selection | null);
        get blockBreakingProgressions(): $Map<$BlockPos, number>;
    }
}
