import { $Bone_ } from "@package/mod/azure/azurelib/common/loading/json/raw";
import { $Record } from "@package/java/lang";
import { $UUID_, $UUID, $List, $List_, $Map } from "@package/java/util";
import { $GeoCube } from "@package/mod/azure/azurelib/common/cache/object";
import { $Matrix4f, $Vector3d, $Matrix3f } from "@package/org/joml";

declare module "@package/mod/azure/azurelib/common/model" {
    export class $AzBakedModel {
        static getDefault(): $AzBakedModel;
        static setDefault(arg0: $AzBakedModel): void;
        deepCopy(): $AzBakedModel;
        getBone(arg0: string): ($AzBone) | undefined;
        getBonesByName(): $Map<string, $AzBone>;
        getTopLevelBones(): $List<$AzBone>;
        getModelUUID(): $UUID;
        getBoneOrNull(arg0: string): $AzBone;
        constructor(arg0: $List_<$AzBone>);
        constructor(arg0: $List_<$AzBone>, arg1: $UUID_);
        get bonesByName(): $Map<string, $AzBone>;
        get topLevelBones(): $List<$AzBone>;
        get modelUUID(): $UUID;
    }
    export class $AzBoneMetadata extends $Record {
        name(): string;
        parent(): $AzBone;
        reset(): boolean;
        inflate(): number;
        mirror(): boolean;
        dontRender(): boolean;
        constructor(arg0: $Bone_, arg1: $AzBone);
        constructor(dontRender: boolean, inflate: number, mirror: boolean, name: string, parent: $AzBone, reset: boolean);
    }
    /**
     * Values that may be interpreted as {@link $AzBoneMetadata}.
     */
    export type $AzBoneMetadata_ = { dontRender?: boolean, reset?: boolean, parent?: $AzBone, mirror?: boolean, inflate?: number, name?: string,  } | [dontRender?: boolean, reset?: boolean, parent?: $AzBone, mirror?: boolean, inflate?: number, name?: string, ];
    export class $AzBoneSnapshot {
        static copy(arg0: $AzBoneSnapshot): $AzBoneSnapshot;
        getOffsetX(): number;
        getOffsetY(): number;
        getRotY(): number;
        getRotX(): number;
        getScaleX(): number;
        getScaleY(): number;
        getBone(): $AzBone;
        updateRotation(arg0: number, arg1: number, arg2: number): void;
        updateScale(arg0: number, arg1: number, arg2: number): void;
        updateOffset(arg0: number, arg1: number, arg2: number): void;
        startPosAnim(): void;
        stopScaleAnim(arg0: number): void;
        stopPosAnim(arg0: number): void;
        stopRotAnim(arg0: number): void;
        startScaleAnim(): void;
        startRotAnim(): void;
        getScaleZ(): number;
        getRotZ(): number;
        isPosAnimInProgress(): boolean;
        isScaleAnimInProgress(): boolean;
        getLastResetRotationTick(): number;
        getLastResetPositionTick(): number;
        getLastResetScaleTick(): number;
        isRotAnimInProgress(): boolean;
        getOffsetZ(): number;
        constructor(arg0: $AzBone);
        get offsetX(): number;
        get offsetY(): number;
        get rotY(): number;
        get rotX(): number;
        get scaleX(): number;
        get scaleY(): number;
        get bone(): $AzBone;
        get scaleZ(): number;
        get rotZ(): number;
        get posAnimInProgress(): boolean;
        get scaleAnimInProgress(): boolean;
        get lastResetRotationTick(): number;
        get lastResetPositionTick(): number;
        get lastResetScaleTick(): number;
        get rotAnimInProgress(): boolean;
        get offsetZ(): number;
    }
    export class $AzBone {
        getName(): string;
        isHidden(): boolean;
        getParent(): $AzBone;
        getMirror(): boolean;
        getPosY(): number;
        getPosX(): number;
        updatePosition(arg0: number, arg1: number, arg2: number): void;
        setRotX(arg0: number): void;
        setRotY(arg0: number): void;
        getRotY(): number;
        getRotX(): number;
        deepCopy(): $AzBone;
        getWorldPosition(): $Vector3d;
        getRotationVector(): $Vector3d;
        setHidden(arg0: boolean): void;
        getScaleX(): number;
        getScaleY(): number;
        setLocalSpaceMatrix(arg0: $Matrix4f): void;
        setWorldSpaceMatrix(arg0: $Matrix4f): void;
        setModelSpaceMatrix(arg0: $Matrix4f): void;
        setScaleZ(arg0: number): void;
        setScaleX(arg0: number): void;
        setScaleY(arg0: number): void;
        setPosY(arg0: number): void;
        setPosX(arg0: number): void;
        updateRotation(arg0: number, arg1: number, arg2: number): void;
        updatePivot(arg0: number, arg1: number, arg2: number): void;
        getScaleVector(): $Vector3d;
        hasRotationChanged(): boolean;
        hasScaleChanged(): boolean;
        getLodHidden(): boolean;
        updateScale(arg0: number, arg1: number, arg2: number): void;
        shouldNeverRender(): boolean;
        markScaleAsChanged(): void;
        setChildrenHidden(arg0: boolean): void;
        resetStateChanges(): void;
        getModelPosition(): $Vector3d;
        getLocalPosition(): $Vector3d;
        setLodHidden(arg0: boolean): void;
        hasPositionChanged(): boolean;
        setModelPosition(arg0: $Vector3d): void;
        getPositionVector(): $Vector3d;
        getModelSpaceMatrix(): $Matrix4f;
        markPositionAsChanged(): void;
        setTrackingMatrices(arg0: boolean): void;
        addRotationOffsetFromBone(arg0: $AzBone): void;
        markRotationAsChanged(): void;
        getWorldSpaceNormal(): $Matrix3f;
        getModelRotationMatrix(): $Matrix4f;
        getLocalSpaceMatrix(): $Matrix4f;
        getInitialAzSnapshot(): $AzBoneSnapshot;
        setWorldSpaceNormal(arg0: $Matrix3f): void;
        getWorldSpaceMatrix(): $Matrix4f;
        getScaleZ(): number;
        getRotZ(): number;
        getInflate(): number;
        getPivotX(): number;
        getPivotZ(): number;
        setPosZ(arg0: number): void;
        getPivotY(): number;
        setPivotY(arg0: number): void;
        setPivotX(arg0: number): void;
        setPivotZ(arg0: number): void;
        setRotZ(arg0: number): void;
        getReset(): boolean;
        getPosZ(): number;
        isTrackingMatrices(): boolean;
        getChildBones(): $List<$AzBone>;
        isHidingChildren(): boolean;
        getCubes(): $List<$GeoCube>;
        saveInitialSnapshot(): void;
        constructor(arg0: $AzBoneMetadata_);
        get name(): string;
        get parent(): $AzBone;
        get mirror(): boolean;
        get worldPosition(): $Vector3d;
        get rotationVector(): $Vector3d;
        get scaleVector(): $Vector3d;
        set childrenHidden(value: boolean);
        get localPosition(): $Vector3d;
        get positionVector(): $Vector3d;
        get modelRotationMatrix(): $Matrix4f;
        get initialAzSnapshot(): $AzBoneSnapshot;
        get inflate(): number;
        get reset(): boolean;
        get childBones(): $List<$AzBone>;
        get hidingChildren(): boolean;
        get cubes(): $List<$GeoCube>;
    }
}
