import { $LevelAccessor } from "@package/net/minecraft/world/level";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $MultiBufferSource_ } from "@package/net/minecraft/client/renderer";
import { $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $SmartBlockEntity } from "@package/com/simibubi/create/foundation/blockEntity";
import { $FilteringBehaviourAccessor } from "@package/net/liukrast/deployer/lib/mixin/accessors";
import { $MutableComponent, $MutableComponent_ } from "@package/net/minecraft/network/chat";
import { $FluidStack_ } from "@package/net/neoforged/neoforge/fluids";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $BehaviourType, $ValueSettingsBoard, $ValueSettingsBehaviour, $BlockEntityBehaviour, $ValueSettingsBehaviour$ValueSettings_, $ValueBoxTransform$Sided, $ValueSettingsBehaviour$ValueSettings, $ValueBoxTransform } from "@package/com/simibubi/create/foundation/blockEntity/behaviour";
import { $InteractionHand_ } from "@package/net/minecraft/world";
import { $Consumer_, $Predicate_, $Supplier_, $BiFunction_ } from "@package/java/util/function";
import { $HolderLookup$Provider, $BlockPos_, $Direction_, $Direction } from "@package/net/minecraft/core";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $Vec3_, $BlockHitResult } from "@package/net/minecraft/world/phys";

declare module "@package/com/simibubi/create/foundation/blockEntity/behaviour/filtering" {
    export class $FilteringRenderer {
        static tick(): void;
        static renderOnBlockEntity(arg0: $SmartBlockEntity, arg1: number, arg2: $PoseStack, arg3: $MultiBufferSource_, arg4: number, arg5: number): void;
        constructor();
    }
    export class $FilteringBehaviour extends $BlockEntityBehaviour implements $ValueSettingsBehaviour, $FilteringBehaviourAccessor {
        test(arg0: $FluidStack_): boolean;
        test(arg0: $ItemStack_): boolean;
        isActive(): boolean;
        getValueSettings(): $ValueSettingsBehaviour$ValueSettings;
        onlyActiveWhen(arg0: $Supplier_<boolean>): $FilteringBehaviour;
        isCountVisible(): boolean;
        getSlotPositioning(): $ValueBoxTransform;
        createBoard(arg0: $Player, arg1: $BlockHitResult): $ValueSettingsBoard;
        onShortInteract(arg0: $Player, arg1: $InteractionHand_, arg2: $Direction_, arg3: $BlockHitResult): void;
        setValueSettings(arg0: $Player, arg1: $ValueSettingsBehaviour$ValueSettings_, arg2: boolean): void;
        showCountWhen(arg0: $Supplier_<boolean>): $FilteringBehaviour;
        getFilter(): $ItemStack;
        getFilter(arg0: $Direction_): $ItemStack;
        setFilter(arg0: $ItemStack_): boolean;
        setFilter(arg0: $Direction_, arg1: $ItemStack_): boolean;
        testHit(arg0: $Vec3_): boolean;
        getClipboardKey(): string;
        readFromClipboard(arg0: $HolderLookup$Provider, arg1: $CompoundTag_, arg2: $Player, arg3: $Direction_, arg4: boolean): boolean;
        writeToClipboard(arg0: $HolderLookup$Provider, arg1: $CompoundTag_, arg2: $Direction_): boolean;
        isRecipeFilter(): boolean;
        canShortInteract(arg0: $ItemStack_): boolean;
        getAmountTip(): $MutableComponent;
        setLabel(arg0: $MutableComponent_): void;
        acceptsValueSettings(): boolean;
        getCountLabelForValueBox(): $MutableComponent;
        getLabel(): $MutableComponent;
        withCallback(arg0: $Consumer_<$ItemStack>): $FilteringBehaviour;
        getMaxStackSize(): number;
        getMaxStackSize(arg0: $Direction_): number;
        getMaxStackSize(arg0: $ItemStack_): number;
        getAmount(): number;
        withPredicate(arg0: $Predicate_<$ItemStack>): $FilteringBehaviour;
        formatValue(arg0: $ValueSettingsBehaviour$ValueSettings_): $MutableComponent;
        forRecipes(): $FilteringBehaviour;
        forFluids(): $FilteringBehaviour;
        anyAmount(): boolean;
        getTip(): $MutableComponent;
        showCount(): $FilteringBehaviour;
        getRenderDistance(): number;
        netId(): number;
        bypassesInput(arg0: $ItemStack_): boolean;
        playFeedbackSound(arg0: $BlockEntityBehaviour): void;
        newSettingHovered(arg0: $ValueSettingsBehaviour$ValueSettings_): void;
        onlyVisibleWithWrench(): boolean;
        mayInteract(arg0: $Player): boolean;
        setValueBoxTransform(arg0: $ValueBoxTransform): void;
        upTo: boolean;
        blockEntity: $SmartBlockEntity;
        count: number;
        customLabel: $MutableComponent;
        static TYPE: $BehaviourType<$FilteringBehaviour>;
        constructor(arg0: $SmartBlockEntity, arg1: $ValueBoxTransform);
        get active(): boolean;
        get countVisible(): boolean;
        get slotPositioning(): $ValueBoxTransform;
        get clipboardKey(): string;
        get recipeFilter(): boolean;
        get amountTip(): $MutableComponent;
        get countLabelForValueBox(): $MutableComponent;
        get amount(): number;
        get tip(): $MutableComponent;
        get renderDistance(): number;
        set valueBoxTransform(value: $ValueBoxTransform);
    }
    export class $SidedFilteringBehaviour extends $FilteringBehaviour {
        get(arg0: $Direction_): $FilteringBehaviour;
        test(arg0: $Direction_, arg1: $ItemStack_): boolean;
        testHit(arg0: $LevelAccessor, arg1: $BlockPos_, arg2: $Direction_, arg3: $Vec3_): boolean;
        removeFilter(arg0: $Direction_): void;
        updateFilterPresence(): void;
        upTo: boolean;
        blockEntity: $SmartBlockEntity;
        count: number;
        customLabel: $MutableComponent;
        static TYPE: $BehaviourType<$FilteringBehaviour>;
        constructor(arg0: $SmartBlockEntity, arg1: $ValueBoxTransform$Sided, arg2: $BiFunction_<$Direction, $FilteringBehaviour, $FilteringBehaviour>, arg3: $Predicate_<$Direction>);
    }
}
