StartupEvents.registry('block', event => {

  //IE
  event.create('chert_lead_ore')
    .displayName('Chert Lead Ore')
    .soundType('stone')
    .hardness(3.0)
    .resistance(3.0)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBoth('c:ores')
    .tagBoth('c:ores/lead')

  event.create('chert_nickel_ore')
    .displayName('Chert Nickel Ore')
    .soundType('stone')
    .hardness(3.0)
    .resistance(3.0)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBoth('c:ores')
    .tagBoth('c:ores/nickel')

  event.create('chert_bauxite_ore')
    .displayName('Chert Bauxite Ore')
    .soundType('stone')
    .hardness(3.0)
    .resistance(3.0)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBoth('c:ores')
    .tagBoth('c:ores/bauxite')

  event.create('nether_uranium_ore')
    .displayName('Nether Uranium Ore')
    .soundType('netherrack')
    .hardness(3.0)
    .resistance(3.0)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBoth('c:ores')
    .tagBoth('c:ores/uranium')

  event.create('nether_thorium_ore')
    .displayName('Nether Thorium Ore')
    .soundType('netherrack')
    .hardness(3.0)
    .resistance(3.0)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBoth('c:ores')
    .tagBoth('c:ores/thorium')

})