// @ULSTICK
global.disabledItems = [

	'alexsmobs:squid_grapple',
	'advancedperipherals:chunk_controller',

	'createaddition:alternator',
	'createaddition:electric_motor',
	'createaddition:connector',
	'createaddition:small_light_connector',
	'createaddition:large_connector',
	'createaddition:copper_spool',
	'createaddition:gold_spool',
	'createaddition:electrum_spool',
	'createaddition:festive_spool',

	'create_connected:copycat_block',
	'create_connected:copycat_slab',
	'create_connected:copycat_beam',
	'create_connected:copycat_vertical_step',
	'create_connected:copycat_stairs',
	'create_connected:copycat_fence',
	'create_connected:copycat_fence_gate',
	'create_connected:copycat_wall',
	'create_connected:copycat_board',
	'create_connected:copycat_box',
	'create_connected:copycat_catwalk',

	'create_new_age:electrical_connector',
	'create_new_age:copper_wire',
	'create_new_age:overcharged_iron_wire',
	'create_new_age:overcharged_golden_wire',
	'create_new_age:overcharged_diamond_wire',

	//'immersiveengineering:connector_hv',
	//'immersiveengineering:connector_hv_relay',
	//'immersiveengineering:connector_lv',
	//'immersiveengineering:connector_lv_relay',
	//'immersiveengineering:connector_mv',
	//'immersiveengineering:connector_mv_relay',
	//'immersiveengineering:wirecoil_copper',
	//'immersiveengineering:wirecoil_copper_ins',
	//'immersiveengineering:wirecoil_electrum',
	//'immersiveengineering:wirecoil_electrum_ins',
	//'immersiveengineering:wirecoil_redstone',
	//'immersiveengineering:wirecoil_steel',
	//'immersiveengineering:wirecoil_structure_rope',
	//'immersiveengineering:wirecoil_structure_steel',

	'create:brass_block',
	'create:brass_ingot',
	'create:brass_nugget',
	'create:brass_sheet',
	'create:brass_casing',
	'create:brass_hand',
	'create:brass_funnel',
	'create:brass_tunnel',
	'create:mechanical_crafter',
	'create:steam_engine',
	'create:smart_chute',
	'create:precision_mechanism',
	'create:electron_tube',
	'create:crushing_wheel',

	'create_sa:steam_engine',

	'steampowered:bronze_steam_engine',
	'steampowered:cast_iron_steam_engine',
	'steampowered:steel_steam_engine',

	'aeronautics:smart_propeller',
	'aeronautics:propeller_bearing',
	'aeronautics:gyroscopic_propeller_bearing',
	'aeronautics:levitite',
	'aeronautics:pearlescent_levitite',
]
