# The maximum height of the radio tower. Including base and head.
# range: 2 - 2147483647
# default: 24
radioTowerMaxHeight = 24
# The minimum height of the radio tower. Including base and head.
# range: 2 - 2147483647
# default: 2
radioTowerMinHeight = 2
# Range per segment.
# range: 1 - 2147483647
# default: 128
radioTowerSegmentRange = 128
# The minimum Y coordinate of the radio tower for maximum effective range.
# range: -2147483648 - 2147483647
# default: 96
radioTowerMinY = 96
# The loss factor of the radio tower.
# range: 0.0 - 1.0
# default: 0.15
radioTowerLossFactor = 0.15
# The maximum message size in bytes.
# range: 1 - 2147483647
# default: 8388608
radioTowerMaxMessageSize = 8388608
# Whether the Mini Antenna can broadcast instead of just receiving.
# default: true
antennaCanBroadcast = true
# The maximum size in bytes of the NFC card and RFID badge data.
# range: 1 - 2147483647
# default: 128
nfcMaxDataSize = 128
# The maximum range of the RFID scanner.
# range: 1 - 2147483647
# default: 8
rfidScanRange = 8
# Enable the Ender Modem nerf.
# default: true
enderModemNerf = true
# Multiplier of the Ender Modem range. The base range is the same as the Wireless Modem.
# range: 0.0 - 1.7976931348623157E308
# default: 2.0
enderModemRangeMultiplier = 2.0
# Ender Modem cross-dimensional range.
# range: 1.0 - 3.4028234663852886E38
# default: 8.0
enderModemCrossDimensionalRange = 8.0
# Enable the improvement of the Redstone Relay event.
# default: true
betterRedstoneRelayEvent = true
