import { $Level } from "@package/net/minecraft/world/level";
import { $DataOutputStream, $File, $DataInputStream, $File_ } from "@package/java/io";
import { $MapDimension } from "@package/xaero/map/world";
import { $BlockTextureColorUtils } from "@package/xaero/lib/client/level/block";
import { $OldFormatSupport, $MapSaveLoad, $RegionDetection, $MapRegionInfo } from "@package/xaero/map/file";
import { $Biome } from "@package/net/minecraft/world/level/biome";
import { $RegionHighlightExistenceTracker } from "@package/xaero/map/highlight";
import { $PoolUnit } from "@package/xaero/map/pool";
import { $RegionTexture, $BranchRegionTexture, $LeafRegionTexture } from "@package/xaero/map/region/texture";
import { $BlockTintProvider } from "@package/xaero/map/biome";
import { $List, $List_, $Hashtable, $ArrayList, $Set } from "@package/java/util";
import { $ByteBuffer } from "@package/java/nio";
import { $BiConsumer_ } from "@package/java/util/function";
import { $BlockPos$MutableBlockPos, $Registry } from "@package/net/minecraft/core";
import { $MapProcessor } from "@package/xaero/map";
import { $BlockState_, $BlockState } from "@package/net/minecraft/world/level/block/state";
import { $ResourceKey_, $ResourceKey } from "@package/net/minecraft/resources";
import { $Block } from "@package/net/minecraft/world/level/block";
import { $FastPalette } from "@package/xaero/map/palette";
import { $Comparable, $Object, $Iterable } from "@package/java/lang";
import { $DimensionType_ } from "@package/net/minecraft/world/level/dimension";
import { $BlockStateShortShapeCache } from "@package/xaero/map/cache";
export * as texture from "@package/xaero/map/region/texture";

declare module "@package/xaero/map/region" {
    export class $Overlay extends $MapPixel {
        equals(arg0: $Overlay): boolean;
        write(arg0: $BlockState_, arg1: number, arg2: boolean): void;
        toRenderString(): string;
        isWater(): boolean;
        getOpacity(): number;
        increaseOpacity(arg0: number): void;
        getPixelColour(arg0: $MapBlock, arg1: number[], arg2: $BlockTextureColorUtils, arg3: $Level, arg4: $MapDimension, arg5: $Registry<$Block>, arg6: $MapTileChunk, arg7: $MapTileChunk, arg8: $MapTileChunk, arg9: $MapTileChunk, arg10: $MapTile, arg11: number, arg12: number, arg13: number, arg14: number, arg15: $BlockPos$MutableBlockPos, arg16: $Registry<$Biome>, arg17: $Registry<$DimensionType_>, arg18: number, arg19: number, arg20: number, arg21: $BlockTintProvider, arg22: $MapProcessor, arg23: $OverlayManager, arg24: $MapUpdateFastConfig): void;
        getParametres(): number;
        constructor(arg0: $BlockState_, arg1: number, arg2: boolean);
        get water(): boolean;
        get opacity(): number;
        get parametres(): number;
    }
    export class $LeveledRegion<T extends $RegionTexture<T>> implements $Comparable<$LeveledRegion<T>> {
        compareTo(arg0: $LeveledRegion<$LeveledRegion<T>>): number;
        getParent(): $BranchLeveledRegion;
        isLoaded(): boolean;
        getLevel(): number;
        shouldCache(): boolean;
        addDebugLines(arg0: $List_<string>, arg1: $MapProcessor, arg2: number, arg3: number): void;
        static setComparison(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): void;
        isMetaLoaded(): boolean;
        getRootRegion(): $LeveledRegion<never>;
        hasTextures(): boolean;
        loadingAnimation(): boolean;
        isRefreshing(): boolean;
        getDim(): $MapDimension;
        checkForUpdates(arg0: $MapProcessor, arg1: boolean, arg2: boolean[], arg3: $ArrayList<$BranchLeveledRegion>, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number): void;
        calculateSortingChunkDistance(): void;
        getTexture(arg0: number, arg1: number): $LeveledRegion<T>;
        onBiomeRemovedFromTexture(arg0: number): void;
        getCaveLayer(): number;
        reloadHasBeenRequested(): boolean;
        setReloadHasBeenRequested(arg0: boolean, arg1: string): void;
        recacheHasBeenRequested(): boolean;
        calculateSortingDistance(): void;
        getBiomePaletteIndex(arg0: $ResourceKey_<$Biome>): number;
        uncountTextureBiomes(arg0: $RegionTexture<never>): void;
        onBiomeAddedToTexture(arg0: $ResourceKey_<$Biome>): number;
        setAllCachePrepared(arg0: boolean): void;
        shouldAffectLoadingRequestFrequency(): boolean;
        getRegionZ(): number;
        getRegionX(): number;
        setRecacheHasBeenRequested(arg0: boolean, arg1: string): void;
        updateLeafTextureVersion(arg0: number, arg1: number, arg2: number): void;
        onDimensionClear(arg0: $MapProcessor): void;
        resetBiomePalette(): void;
        deleteBuffers(): void;
        deleteGLBuffers(): void;
        getBiomePaletteSize(): number;
        deleteTexturesAndBuffers(): void;
        shouldAllowAnotherRegionToLoad(): boolean;
        putTexture(arg0: number, arg1: number, arg2: $LeveledRegion<T>): void;
        getCacheFile(): $File;
        setShouldCache(arg0: boolean, arg1: string): void;
        loadCacheTextures(arg0: $MapProcessor, arg1: $Registry<$Biome>, arg2: boolean, arg3: boolean[][], arg4: number, arg5: boolean[], arg6: boolean[], arg7: number, arg8: $OldFormatSupport): boolean;
        createTexture(arg0: number, arg1: number): $LeveledRegion<T>;
        setCacheFile(arg0: $File_): void;
        processWhenLoadedChunksExist(arg0: number): void;
        preCache(): void;
        postCache(arg0: $File_, arg1: $MapSaveLoad, arg2: boolean): void;
        skipCaching(arg0: number): boolean;
        findCacheFile(arg0: $MapSaveLoad): $File;
        onProcessingEnd(): void;
        onCurrentDimFinish(arg0: $MapSaveLoad, arg1: $MapProcessor): void;
        shouldBeProcessed(): boolean;
        getExtraInfo(): string;
        onLimiterRemoval(arg0: $MapProcessor): void;
        cleanAndCacheRequestsBlocked(): boolean;
        shouldEndProcessingAfterUpload(): boolean;
        afterLimiterRemoval(arg0: $MapProcessor): void;
        hasRemovableSourceData(): boolean;
        getAndResetCachedTextureVersion(arg0: number, arg1: number): number;
        isAllCachePrepared(): boolean;
        confirmMetaLoaded(): void;
        getBiomePalette(): $FastPalette<$ResourceKey<$Biome>>;
        saveCacheTextures(arg0: $File_, arg1: boolean, arg2: number): boolean;
        getBiomeKey(arg0: number): $ResourceKey<$Biome>;
        ensureBiomePalette(): void;
        saveBiomePalette(arg0: $DataOutputStream): void;
        activeBranchUpdateReferences: number;
        leafTextureVersionSum: number[][];
        static SIDE_LENGTH: number;
        constructor(arg0: string, arg1: string, arg2: string, arg3: $MapDimension, arg4: number, arg5: number, arg6: number, arg7: number, arg8: $BranchLeveledRegion);
        get parent(): $BranchLeveledRegion;
        get loaded(): boolean;
        get level(): number;
        get metaLoaded(): boolean;
        get rootRegion(): $LeveledRegion<never>;
        get refreshing(): boolean;
        get dim(): $MapDimension;
        get caveLayer(): number;
        get regionZ(): number;
        get regionX(): number;
        get biomePaletteSize(): number;
        get extraInfo(): string;
        get biomePalette(): $FastPalette<$ResourceKey<$Biome>>;
    }
    export class $MapRegion extends $LeveledRegion<$LeafRegionTexture> implements $MapRegionInfo {
        clean(arg0: $MapProcessor): void;
        getVersion(): number;
        getLastSaveTime(): number;
        setSaveExists(arg0: boolean): void;
        getInitialVersion(): number;
        setInitialVersion(arg0: number): void;
        setParent(arg0: $BranchLeveledRegion): void;
        getCacheHashCode(): number;
        hasHadTerrain(): boolean;
        getReloadVersion(): number;
        getBiomeRegistry(): $Registry<$Biome>;
        getCaveStart(): number;
        getLoadState(): number;
        caveStartOutdated(arg0: number, arg1: number): boolean;
        getHighlightsHash(): number;
        setRefreshing(arg0: boolean): void;
        hasVersion(): boolean;
        setLastSaveTime(arg0: number): void;
        setVersion(arg0: number): void;
        getTexture(arg0: number, arg1: number): $LeafRegionTexture;
        getDimId(): string;
        setRegionFile(arg0: $File_): void;
        isResting(): boolean;
        getChunk(arg0: number, arg1: number): $MapTileChunk;
        registerVisit(): void;
        setBeingWritten(arg0: boolean): void;
        isWritingPaused(): boolean;
        setLoadState(arg0: number): void;
        isNormalMapData(): boolean;
        setHasHadTerrain(): void;
        canRequestReload_unsynced(): boolean;
        setOutdatedWithOtherLayers(arg0: boolean): void;
        destroyBufferUpdateObjects(): void;
        updateTargetHighlightsHash(): void;
        getTargetHighlightsHash(): number;
        isOutdatedWithOtherLayers(): boolean;
        pushWriterPause(): void;
        popWriterPause(): void;
        getSaveExists(): boolean;
        setCacheHashCode(arg0: number): void;
        cancelRefresh(arg0: $MapProcessor): void;
        clearRegion(arg0: $MapProcessor): void;
        countChunks(): number;
        getRegionFile(): $File;
        setHighlightsHash(arg0: number): void;
        setCaveStart(arg0: number): void;
        requestRefresh(arg0: $MapProcessor): void;
        requestRefresh(arg0: $MapProcessor, arg1: boolean): void;
        getMwId(): string;
        putTexture(arg0: number, arg1: number, arg2: $LeafRegionTexture): void;
        getWorldId(): string;
        hasLookedForCache(): boolean;
        createTexture(arg0: number, arg1: number): $LeafRegionTexture;
        isBeingWritten(): boolean;
        setChunk(arg0: number, arg1: number, arg2: $MapTileChunk): void;
        isResaving(): boolean;
        getTimeSinceVisit(): number;
        setLookedForCache(arg0: boolean): void;
        unsetHasHadTerrain(): void;
        updateCaveMode(arg0: $MapProcessor): void;
        getCaveDepth(): number;
        setReloadVersion(arg0: number): void;
        restoreMetaData(arg0: number[][], arg1: number, arg2: number, arg3: number, arg4: number, arg5: boolean, arg6: $MapProcessor): void;
        setResaving(arg0: boolean): void;
        getLastVisited(): number;
        restoreBufferUpdateObjects(): void;
        getMutableGlobalPos(): $BlockPos$MutableBlockPos;
        getUpToDateCaveStart(): number;
        getPixelResultBuffer(): number[];
        convertCacheToOutdated(arg0: $MapSaveLoad, arg1: string): void;
        shouldConvertCacheToOutdatedOnFinishDim(): boolean;
        activeBranchUpdateReferences: number;
        leafTextureVersionSum: number[][];
        loadingNeededForBranchLevel: number;
        writerThreadPauseSync: $Object;
        static SIDE_LENGTH: number;
        loadingPrioritized: boolean;
        constructor(arg0: string, arg1: string, arg2: string, arg3: $MapDimension, arg4: number, arg5: number, arg6: number, arg7: number, arg8: boolean, arg9: $Registry<$Biome>);
        set parent(value: $BranchLeveledRegion);
        get biomeRegistry(): $Registry<$Biome>;
        set refreshing(value: boolean);
        get dimId(): string;
        get resting(): boolean;
        get writingPaused(): boolean;
        get normalMapData(): boolean;
        get targetHighlightsHash(): number;
        get mwId(): string;
        get worldId(): string;
        get timeSinceVisit(): number;
        set lookedForCache(value: boolean);
        get caveDepth(): number;
        get lastVisited(): number;
        get mutableGlobalPos(): $BlockPos$MutableBlockPos;
        get upToDateCaveStart(): number;
        get pixelResultBuffer(): number[];
    }
    export class $LayeredRegionManager {
        remove(arg0: number, arg1: number, arg2: number, arg3: number): boolean;
        size(): number;
        get(arg0: number, arg1: number, arg2: number, arg3: number): $LeveledRegion<never>;
        clear(): void;
        getLayer(arg0: number): $MapLayer;
        loadedCount(): number;
        getLeaf(arg0: number, arg1: number, arg2: number): $MapRegion;
        bumpLoadedRegion(arg0: $MapRegion): void;
        bumpLoadedRegion(arg0: $LeveledRegion<never>): void;
        addListRegion(arg0: $LeveledRegion<never>): void;
        applyToEachLoadedLayer(arg0: $BiConsumer_<number, $MapLayer>): void;
        onClearCachedHighlightHashes(): void;
        onClearCachedHighlightHash(arg0: number, arg1: number): void;
        getUnsyncedSet(): $Set<$LeveledRegion<never>>;
        putLeaf(arg0: number, arg1: number, arg2: $MapRegion): void;
        addLoadedRegion(arg0: $LeveledRegion<never>): void;
        removeListRegion(arg0: $LeveledRegion<never>): void;
        removeLoadedRegion(arg0: $LeveledRegion<never>): void;
        preDetection(): void;
        getLoadedListUnsynced(): $List<$LeveledRegion<never>>;
        getLoadedRegion(arg0: number): $LeveledRegion<never>;
        constructor(arg0: $MapDimension);
        get unsyncedSet(): $Set<$LeveledRegion<never>>;
        get loadedListUnsynced(): $List<$LeveledRegion<never>>;
    }
    export class $MapTileChunk {
        clean(arg0: $MapProcessor): void;
        getTile(arg0: number, arg1: number): $MapTile;
        getX(): number;
        hasHadTerrain(): boolean;
        getLoadState(): number;
        hasHighlightsIfUndiscovered(): boolean;
        getTimer(): number;
        getTileGridsCache(): number[][];
        getLeafTexture(): $LeafRegionTexture;
        setChanged(arg0: boolean): void;
        putColour(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: $ByteBuffer, arg7: number): void;
        updateBuffers(arg0: $MapProcessor, arg1: $BlockTintProvider, arg2: $OverlayManager, arg3: boolean, arg4: $BlockStateShortShapeCache, arg5: $MapUpdateFastConfig): void;
        setLoadState(arg0: number): void;
        setHasHadTerrain(): void;
        setToUpdateBuffers(arg0: boolean): void;
        includeInSave(): boolean;
        setTile(arg0: number, arg1: number, arg2: $MapTile, arg3: $BlockStateShortShapeCache, arg4: $MapProcessor): void;
        getNeighbourTileChunk(arg0: number, arg1: number, arg2: $MapProcessor, arg3: boolean): $MapTileChunk;
        getZ(): number;
        wasChanged(): boolean;
        unsetHasHadTerrain(): void;
        getInRegion(): $MapRegion;
        writeCacheData(arg0: $DataOutputStream, arg1: number[], arg2: number[], arg3: $LeveledRegion<$LeafRegionTexture>): void;
        hasHighlights(): boolean;
        unincludeInSave(): void;
        setHasHighlights(arg0: boolean): void;
        setHasHighlightsIfUndiscovered(arg0: boolean): void;
        decTimer(): void;
        resetHeights(): void;
        getToUpdateBuffers(): boolean;
        readCacheData(arg0: number, arg1: number, arg2: $DataInputStream, arg3: number[], arg4: number[], arg5: $MapProcessor, arg6: number, arg7: number): void;
        static SIDE_LENGTH: number;
        constructor(arg0: $MapRegion, arg1: number, arg2: number);
        get x(): number;
        get timer(): number;
        get tileGridsCache(): number[][];
        get leafTexture(): $LeafRegionTexture;
        set changed(value: boolean);
        get z(): number;
        get inRegion(): $MapRegion;
    }
    export class $BranchLeveledRegion extends $LeveledRegion<$BranchRegionTexture> {
        isEmpty(): boolean;
        setLoaded(arg0: boolean): void;
        getTexture(arg0: number, arg1: number): $BranchRegionTexture;
        startDownloadingTexturesForCache(arg0: $MapProcessor): void;
        setShouldCheckForUpdatesSingle(arg0: boolean): void;
        setShouldCheckForUpdatesRecursive(arg0: boolean): void;
        putTexture(arg0: number, arg1: number, arg2: $BranchRegionTexture): void;
        createTexture(arg0: number, arg1: number): $BranchRegionTexture;
        postTextureUpdate(): void;
        eligibleForSaving(arg0: number): boolean;
        preCacheLoad(): void;
        activeBranchUpdateReferences: number;
        static CHILD_LENGTH_IN_TEXTURES: number;
        leafTextureVersionSum: number[][];
        static SIDE_LENGTH: number;
        static MAX_COORD_WITHIN_CHILD: number;
        constructor(arg0: string, arg1: string, arg2: string, arg3: $MapDimension, arg4: number, arg5: number, arg6: number, arg7: number, arg8: $BranchLeveledRegion);
        get empty(): boolean;
        set loaded(value: boolean);
        set shouldCheckForUpdatesSingle(value: boolean);
        set shouldCheckForUpdatesRecursive(value: boolean);
    }
    export class $OverlayManager {
        getOriginal(arg0: $Overlay): $Overlay;
        getNumberOfUniqueOverlays(): number;
        constructor();
        get numberOfUniqueOverlays(): number;
    }
    export class $MapLayer {
        getCaveStart(): number;
        getRegionHighlightExistenceTracker(): $RegionHighlightExistenceTracker;
        getLinkedCompleteWorldSaveDetectedRegions(): $Iterable<$RegionDetection>;
        tryAddingToCompleteRegionDetection(arg0: $RegionDetection): void;
        getCompleteRegionDetection(arg0: number, arg1: number): $RegionDetection;
        removeRegionDetection(arg0: number, arg1: number): void;
        addRegionDetection(arg0: $RegionDetection): void;
        setCaveStart(arg0: number): void;
        getRegionDetection(arg0: number, arg1: number): $RegionDetection;
        getDetectedRegions(): $Hashtable<number, $Hashtable<number, $RegionDetection>>;
        regionDetectionExists(arg0: number, arg1: number): boolean;
        getMapRegions(): $LeveledRegionManager;
        preDetection(): void;
        constructor(arg0: $MapDimension, arg1: $RegionHighlightExistenceTracker);
        get regionHighlightExistenceTracker(): $RegionHighlightExistenceTracker;
        get linkedCompleteWorldSaveDetectedRegions(): $Iterable<$RegionDetection>;
        get detectedRegions(): $Hashtable<number, $Hashtable<number, $RegionDetection>>;
        get mapRegions(): $LeveledRegionManager;
    }
    export class $MapPixel {
        getState(): $BlockState;
        setState(arg0: $BlockState_): void;
        setGlowing(arg0: boolean): void;
        getBlockBrightness(arg0: number, arg1: number, arg2: number): number;
        setLight(arg0: number): void;
        getPixelColours(arg0: number[], arg1: $BlockTextureColorUtils, arg2: $Level, arg3: $MapDimension, arg4: $Registry<$Block>, arg5: $MapTileChunk, arg6: $MapTileChunk, arg7: $MapTileChunk, arg8: $MapTileChunk, arg9: $MapTile, arg10: number, arg11: number, arg12: $MapBlock, arg13: number, arg14: number, arg15: number, arg16: number, arg17: $ArrayList<$Overlay>, arg18: $BlockPos$MutableBlockPos, arg19: $Registry<$Biome>, arg20: $Registry<$DimensionType_>, arg21: number, arg22: number, arg23: number, arg24: $BlockTintProvider, arg25: $MapProcessor, arg26: $OverlayManager, arg27: $BlockStateShortShapeCache, arg28: $MapUpdateFastConfig): void;
        constructor();
        set glowing(value: boolean);
        set light(value: number);
    }
    export class $MapUpdateFastConfig {
        stainedGlass: boolean;
        terrainDepth: boolean;
        biomeColorsInVanilla: boolean;
        adjustHeightForShortBlocks: boolean;
        biomeBlending: boolean;
        blockColors: number;
        legibleCaveMaps: boolean;
        terrainSlopes: number;
        constructor(arg0: $MapProcessor);
    }
    export class $MapTile implements $PoolUnit {
        create(...arg0: $Object[]): void;
        isLoaded(): boolean;
        getBlock(arg0: number, arg1: number): $MapBlock;
        setLoaded(arg0: boolean): void;
        setWorldInterpretationVersion(arg0: number): void;
        setBlock(arg0: number, arg1: number, arg2: $MapBlock): void;
        wasWrittenOnce(): boolean;
        setWrittenCave(arg0: number, arg1: number): void;
        setWrittenOnce(arg0: boolean): void;
        getWrittenCaveStart(): number;
        getWrittenCaveDepth(): number;
        getBlockColumn(arg0: number): $MapBlock[];
        getWorldInterpretationVersion(): number;
        getChunkX(): number;
        getChunkZ(): number;
        static CURRENT_WORLD_INTERPRETATION_VERSION: number;
        constructor(...arg0: $Object[]);
        set writtenOnce(value: boolean);
        get writtenCaveStart(): number;
        get writtenCaveDepth(): number;
        get chunkX(): number;
        get chunkZ(): number;
    }
    export class $MapBlock extends $MapPixel {
        equals(arg0: $MapBlock, arg1: boolean): boolean;
        write(arg0: $BlockState_, arg1: number, arg2: number, arg3: $ResourceKey_<$Biome>, arg4: number, arg5: boolean, arg6: boolean): void;
        getHeight(): number;
        getTopHeight(): number;
        toRenderString(arg0: $Registry<$Biome>): string;
        getOverlays(): $ArrayList<$Overlay>;
        setBiome(arg0: $ResourceKey_<$Biome>): void;
        getEffectiveHeight(arg0: $BlockStateShortShapeCache, arg1: $MapUpdateFastConfig): number;
        getEffectiveHeight(arg0: boolean): number;
        fixHeightType(arg0: number, arg1: number, arg2: $MapTile, arg3: $MapTileChunk, arg4: $MapTileChunk, arg5: $MapTileChunk, arg6: $MapTileChunk, arg7: number, arg8: boolean, arg9: $BlockStateShortShapeCache, arg10: $MapUpdateFastConfig): void;
        setSlopeUnknown(arg0: boolean): void;
        prepareForWriting(arg0: number): void;
        getNumberOfOverlays(): number;
        equalsSlopesExcluded(arg0: $MapBlock): boolean;
        getBiome(): $ResourceKey<$Biome>;
        setHeight(arg0: number): void;
        setDiagonalSlope(arg0: number): void;
        getVerticalSlope(): number;
        getPixelColour(arg0: number[], arg1: $BlockTextureColorUtils, arg2: $Level, arg3: $MapDimension, arg4: $Registry<$Block>, arg5: $MapTileChunk, arg6: $MapTileChunk, arg7: $MapTileChunk, arg8: $MapTileChunk, arg9: $MapTile, arg10: number, arg11: number, arg12: number, arg13: number, arg14: $BlockPos$MutableBlockPos, arg15: $Registry<$Biome>, arg16: $Registry<$DimensionType_>, arg17: number, arg18: number, arg19: number, arg20: $BlockTintProvider, arg21: $MapProcessor, arg22: $OverlayManager, arg23: number, arg24: number, arg25: $BlockStateShortShapeCache, arg26: $MapUpdateFastConfig): void;
        getDiagonalSlope(): number;
        getParametres(): number;
        setTopHeight(arg0: number): void;
        setVerticalSlope(arg0: number): void;
        getEffectiveTopHeight(arg0: boolean): number;
        isGrass(): boolean;
        addOverlay(arg0: $Overlay): void;
        constructor();
        get overlays(): $ArrayList<$Overlay>;
        set slopeUnknown(value: boolean);
        get numberOfOverlays(): number;
        get parametres(): number;
        get grass(): boolean;
    }
    export class $LeveledRegionManager {
        remove(arg0: number, arg1: number, arg2: number): boolean;
        get(arg0: number, arg1: number, arg2: number): $LeveledRegion<never>;
        getLeaf(arg0: number, arg1: number): $MapRegion;
        putLeaf(arg0: number, arg1: number, arg2: $MapRegion): void;
        static MAX_LEVEL: number;
        constructor();
    }
}
