import { $GlBufferArena } from "@package/net/caffeinemc/mods/sodium/client/gl/arena";
import { $CommandList, $MultiDrawBatch } from "@package/net/caffeinemc/mods/sodium/client/gl/device";
import { $GlTessellation } from "@package/net/caffeinemc/mods/sodium/client/gl/tessellation";
import { $RenderSection } from "@package/net/caffeinemc/mods/sodium/client/render/chunk";
import { $SectionRenderDataStorage } from "@package/net/caffeinemc/mods/sodium/client/render/chunk/data";
import { $ChunkRenderList } from "@package/net/caffeinemc/mods/sodium/client/render/chunk/lists";
import { $StagingBuffer } from "@package/net/caffeinemc/mods/sodium/client/gl/arena/staging";
import { $GlBuffer } from "@package/net/caffeinemc/mods/sodium/client/gl/buffer";
import { $TerrainRenderPass } from "@package/net/caffeinemc/mods/sodium/client/render/chunk/terrain";
import { $RenderRegionExtension } from "@package/foundry/veil/forge/ext";

declare module "@package/net/caffeinemc/mods/sodium/client/render/chunk/region" {
    export class $RenderRegion$DeviceResources {
        "delete"(arg0: $CommandList): void;
        getGeometryArena(): $GlBufferArena;
        getIndexArena(): $GlBufferArena;
        shouldDelete(): boolean;
        updateTessellation(arg0: $CommandList, arg1: $GlTessellation): void;
        getTessellation(): $GlTessellation;
        getGeometryBuffer(): $GlBuffer;
        getIndexBuffer(): $GlBuffer;
        deleteTessellation(arg0: $CommandList): void;
        deleteIndexedTessellation(arg0: $CommandList): void;
        updateIndexedTessellation(arg0: $CommandList, arg1: $GlTessellation): void;
        getIndexedTessellation(): $GlTessellation;
        constructor(arg0: $CommandList, arg1: $StagingBuffer);
        get geometryArena(): $GlBufferArena;
        get indexArena(): $GlBufferArena;
        get tessellation(): $GlTessellation;
        get geometryBuffer(): $GlBuffer;
        get indexBuffer(): $GlBuffer;
        get indexedTessellation(): $GlTessellation;
    }
    export class $RenderRegion implements $RenderRegionExtension {
        update(arg0: $CommandList): void;
        isEmpty(): boolean;
        getResources(): $RenderRegion$DeviceResources;
        static key(arg0: number, arg1: number, arg2: number): number;
        "delete"(arg0: $CommandList): void;
        getX(): number;
        addSection(arg0: $RenderSection): void;
        getStorage(arg0: $TerrainRenderPass): $SectionRenderDataStorage;
        getSection(arg0: number): $RenderSection;
        createStorage(arg0: $TerrainRenderPass): $SectionRenderDataStorage;
        getRenderList(): $ChunkRenderList;
        getCachedBatch(arg0: $TerrainRenderPass): $MultiDrawBatch;
        getFillFractionInv(): number;
        refreshTesselation(arg0: $CommandList): void;
        createResources(arg0: $CommandList): $RenderRegion$DeviceResources;
        getY(): number;
        getZ(): number;
        removeSection(arg0: $RenderSection): void;
        veil$getPerspectiveRenderList(): $ChunkRenderList;
        getOriginX(): number;
        getOriginY(): number;
        getChunkY(): number;
        getOriginZ(): number;
        clearCachedBatchFor(arg0: $TerrainRenderPass): void;
        clearAllCachedBatches(): void;
        refreshIndexedTesselation(arg0: $CommandList): void;
        getChunkX(): number;
        getChunkZ(): number;
        static SECTION_INDEX_COUNT_ESTIMATE: number;
        static REGION_WIDTH: number;
        static REGION_HEIGHT_M: number;
        static REGION_WIDTH_SH: number;
        static REGION_LENGTH_M: number;
        static REGION_SIZE: number;
        static SECTION_BUFFER_ESTIMATE: number;
        static SECTION_VERTEX_COUNT_ESTIMATE: number;
        static REGION_LENGTH: number;
        static REGION_LENGTH_SH: number;
        static REGION_WIDTH_M: number;
        static REGION_HEIGHT_SH: number;
        static REGION_HEIGHT: number;
        constructor(arg0: number, arg1: number, arg2: number, arg3: $StagingBuffer);
        get empty(): boolean;
        get resources(): $RenderRegion$DeviceResources;
        get x(): number;
        get renderList(): $ChunkRenderList;
        get fillFractionInv(): number;
        get y(): number;
        get z(): number;
        get originX(): number;
        get originY(): number;
        get chunkY(): number;
        get originZ(): number;
        get chunkX(): number;
        get chunkZ(): number;
    }
}
